#include <iostream> 
using namespace std; 
  
void fun() 
{ 
    int x = -1; 
  
    // Some code 
    if (x < 0) 
    { 
        throw x; 
        cout << "After throw (Never executed)"; 
    } 
} 
  
int main() 
{ 
    try
    { 
        fun(); 
    } 
    catch (int x) 
    { 
        cout << "Exception Caught"; 
    } 
  
    return 0; 
}
